language: R
sudo: required
warnings_are_errors: true

env: 
  global:
    - CRAN: https://cran.rstudio.com
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"

# desperately trying to shorten outrageous dep install times...
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -qq r-cran-bitops r-cran-catools r-cran-digest r-cran-evaluate r-cran-ggplot2 r-cran-memoise r-cran-scales r-cran-slam r-cran-stringr 

r_packages:
  - slam
  - memuse
  - microbenchmark
  - rbenchmark
  - knitr
  - rmarkdown

r_check_args: --no-build-vignettes --no-manual
